### PR TITLE
How should the script be used correctly?

### PR DESCRIPTION
**Pull request by ss958**
How should the script be used correctly?

### CODE REVIEW

**Comment by talamortis** [comment]
this is not an issue

**Comment by ss958** [comment]
I mount the script and the number of rool set at SQL and the corresponding reward items.
How do you play this game in the game?

**Comment by talamortis** [comment]
This is not an in game script. This script works in the background for the players, you assign rolls to the item in the database using the sql provided  and after a couple of hours the player will automatically roll, if the roll is assigned the item will be given.

**Comment by ss958** [comment]
I didn't find a place to modify the interval. I wanted to test the script.

**Comment by ss958** [comment]
How many hours can the time be adjusted? For example, how many minutes?

**Pull request closed without merging**
